/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Auto;
import javax.swing.JInternalFrame;

/**
 *
 * @author USER
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAuto = new javax.swing.JMenuItem();
        mnuPropietario = new javax.swing.JMenuItem();
        mnuMatricula = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        mnuAuto.setText("Auto");
        mnuAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAutoActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAuto);

        mnuPropietario.setText("Propietario");
        mnuPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPropietarioActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPropietario);

        mnuMatricula.setText("Matricula");
        mnuMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMatriculaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuMatricula);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajustes");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAutoActionPerformed
        // TODO add your handling code here:
        var auto = new AutoVentana();
        auto.setIconifiable(true);
        auto.setClosable(true);
        auto.setResizable(true);
        this.jDesktopPane2.add(auto);
        auto.setVisible(true);
        auto.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        
        
        
        
    }//GEN-LAST:event_mnuAutoActionPerformed

    private void mnuMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMatriculaActionPerformed
        // TODO add your handling code here:
        var matricula = new MatriculaVentana();
        matricula.setIconifiable(true);
        matricula.setClosable(true);
        matricula.setResizable(true);
        this.jDesktopPane2.add(matricula);
        matricula.setVisible(true);
        matricula.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_mnuMatriculaActionPerformed

    private void mnuPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPropietarioActionPerformed
        // TODO add your handling code here:
        var propietario = new PropietarioVentana();
        propietario.setIconifiable(true);
        propietario.setClosable(true);
        propietario.setResizable(true);
        this.jDesktopPane2.add(propietario);
        propietario.setVisible(true);
        propietario.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_mnuPropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAuto;
    private javax.swing.JMenuItem mnuMatricula;
    private javax.swing.JMenuItem mnuPropietario;
    // End of variables declaration//GEN-END:variables
}
